### ISSUE TITLE
AttributeError, 'function' has no attribute 'devices'

### ISSUE THREAD

**Issue by nielsuit227** [outlines-dev/outlines#260] opened 2023-08-23 14:22 UTC
Taking one of the examples of the readme, and replacing gpt-2 by gpt-3.5 that I found in one of the examples, results in an error on my device. Running MacOS 13.4, Python 3.10. Let me know if you need to know other dependencies. Or if I can help bugfix :) Reckon it's OS related given the torch dependency, but haven't dug in the code. 

Code:
```python
import outlines.models as models
import outlines.text.generate as generate

model = models.text_completion.openai("gpt-3.5-turbo")

prompt = "Is 1+1=2? "
unguided = generate.continuation(model, max_tokens=30)(prompt)
guided = generate.regex(model, r"\s*([Yy]es|[Nn]o|[Nn]ever|[Aa]lways)", max_tokens=30)(prompt)

print("unguided: ", unguided)
# Is 1+1=2?
#
# This is probably the most perplexing question.
# As I said in one of my articles describing how
# I call 2 and 1, there isn't

print("guided: ", guided)
# # Is 1+1=2? Always
```

Traceback:
```text
Traceback (most recent call last):
  File "/exeriment_outline.py", line 10, in <module>
    unguided = generate.continuation(model, max_tokens=30)(prompt)
  File "/Users/n/miniconda3/envs/c/lib/python3.10/site-packages/outlines/text/generate/continuation.py", line 107, in continuation
    return Continuation(model, max_tokens, stop)
  File "/Users/n/miniconda3/envs/c/lib/python3.10/site-packages/outlines/text/generate/continuation.py", line 23, in __init__
    super().__init__(model, max_tokens)
  File "/Users/n/miniconda3/envs/c/lib/python3.10/site-packages/outlines/text/generate/sequence.py", line 22, in __init__
    self.device = model.device
AttributeError: 'function' object has no attribute 'device'
```

**Comment by massi-ang** [comment] 2023-08-29 07:45
This seems to be related to the fact the the code assume the model is running locally, and not via a remote API

**Comment by brandonwillard** [comment] 2023-09-11 19:52
This appears to be a duplicate of #227.

**Closed by brandonwillard** 2023-09-11 19:52 UTC
Labels: bug
