### ISSUE TITLE
Issue with JSON generation example in Readme

### ISSUE THREAD

**Issue by tranhoangnguyen03** [outlines-dev/outlines#275] opened 2023-09-11 08:20 UTC
I copy-paste the example in Readme directly and get this error:
```
from enum import Enum
from pydantic import BaseModel, constr

import outlines.models as models
import outlines.text.generate as generate

import torch


class Weapon(str, Enum):
    sword = "sword"
    axe = "axe"
    mace = "mace"
    spear = "spear"
    bow = "bow"
    crossbow = "crossbow"


class Armor(str, Enum):
    leather = "leather"
    chainmail = "chainmail"
    plate = "plate"


class Character(BaseModel):
    name: constr(max_length=10)
    age: int
    armor: Armor
    weapon: Weapon
    strength: int


model = models.transformers("gpt2", device="cuda")

# Construct guided sequence generator
generator = generate.json(model, Character, max_tokens=100)

# Draw a sample
rng = torch.Generator(device="cuda")
rng.manual_seed(789001)

sequence = generator("Give me a character description", rng=rng)
print(sequence)
# {
#   "name": "clerame",
#   "age": 7,
#   "armor": "plate",
#   "weapon": "mace",
#   "strength": 4171
# }

sequence = generator("Give me an interesting character description", rng=rng)
print(sequence)
# {
#   "name": "piggyback",
#   "age": 23,
#   "armor": "chainmail",
#   "weapon": "sword",
#   "strength": 0
# }

parsed = Character.model_validate_json(sequence)
print(parsed)
# name='piggyback' age=23 armor=<Armor.chainmail: 'chainmail'> weapon=<Weapon.sword: 'sword'> strength=0
```

```
AttributeError                            Traceback (most recent call last)
[<ipython-input-50-aaec93d1ab96>](https://localhost:8080/#) in <cell line: 32>()
     30 
     31 model = models.transformers("gpt2")
---> 32 sequence = generate.json(model, Character)("Give me a character description")
     33 print(sequence)
     34 # {

[/usr/local/lib/python3.10/dist-packages/outlines/text/generate/regex.py](https://localhost:8080/#) in json(model, schema, max_tokens)
    224     """
    225     if isinstance(schema, type(BaseModel)):
--> 226         schema = dumps(schema.model_json_schema())
    227 
    228     regex_str = build_regex_from_schema(schema)

AttributeError: type object 'Character' has no attribute 'model_json_schema'
```

**Comment by tranhoangnguyen03** [comment] 2023-09-11 08:24
Attempt to put constraint on response model:
```
from pydantic import BaseModel
import outlines.text as text

class JokeType(str, Enum):
    dark = "dark"
    light = "light"

class Joke(BaseModel):
    joke: str
    type: JokeType
    explanation: str


@text.prompt
def joke_ppt(response_model):
    """Tell a joke and explain why the joke is funny.

    RESPONSE FORMAT:
    {{ response_model | schema }}
    """

model = LLMModels.get_model(
    text_length = 200,
    version='gpt-3.5')

prompt = joke_ppt(Joke)
joke_res = model(prompt)
```

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-51-c6ec24263b71>](https://localhost:8080/#) in <cell line: 28>()
     26     version='gpt-3.5')
     27 
---> 28 prompt = joke_ppt(Joke)
     29 reformatted = model(prompt)

7 frames
<template> in top-level template code()

[/usr/local/lib/python3.10/dist-packages/outlines/text/prompts.py](https://localhost:8080/#) in parse_pydantic_schema(raw_schema, definitions)
    312     """
    313     simple_schema = {}
--> 314     for name, value in raw_schema["properties"].items():
    315         if "description" in value:
    316             simple_schema[name] = value["description"]

KeyError: 'properties'
```

**Comment by brandonwillard** [comment] 2023-09-11 19:44
Can you provide a complete [MWE](https://en.wikipedia.org/wiki/Minimal_reproducible_example)?

**Comment by tranhoangnguyen03** [comment] 2023-09-12 09:58
> Can you provide a complete [MWE](https://en.wikipedia.org/wiki/Minimal_reproducible_example)?

I made edit to original issue

**Comment by AntanasKascenas** [comment] 2023-09-12 10:54
What is your version of pydantic? I've had this error when trying to run this with pydantic<2.0.

**Comment by rlouf** [comment] 2023-09-13 06:46
> What is your version of pydantic? I've had this error when trying to run this with pydantic<2.0.

This is indeed the issue here. @tranhoangnguyen03 can you try installing Pydantic >= 2.0 and re-running your example?

**Comment by tranhoangnguyen03** [comment] 2023-09-13 12:14
I've manged to make it work by adding the ` Field(..., description="type: str desc: Joke type, either 'dark' or 'light' ")`. It seems that when converted to prompt, only the attribute name and the description get transfered over to the prompt context. Is this WAD?

**Comment by brandonwillard** [comment] 2023-09-13 15:12
It looks like the issue was due to an old version of Pedantic, so I'm going to close this; otherwise, the last error is a duplicate of #229.

**Closed by brandonwillard** 2023-09-13 15:12 UTC
