### ISSUE TITLE
Docstring of `RegexLogitsProcessor` is incorrect

### ISSUE THREAD

**Issue by sethkimmel3** [outlines-dev/outlines#624] opened 2024-02-08 06:01 UTC
### Describe the issue as clearly as possible:

Related to #536, the JSONLogitsProcessor requires the same `adapt_tokenizer` modifications found [here](https://github.com/outlines-dev/outlines/blob/7fae436345e621a955e1e6ea610f74cf59f9466f/outlines/serve/vllm.py#L80), otherwise it throws this error: `AttributeError: 'LLM' object has no attribute 'tokenizer'`.

### Steps/code to reproduce the bug:

```python
from vllm import LLM
from outlines.serve.vllm import JSONLogitsProcessor, _patched_apply_logits_processors
from pydantic import BaseModel
from vllm import SamplingParams
import vllm.model_executor.layers.sampler as sampler

sampler._apply_logits_processors = _patched_apply_logits_processors

llm = LLM('mistralai/Mistral-7B-Instruct-v0.1')

class AviationPrompt(BaseModel):
    is_aviation_related: bool

logits_processor = JSONLogitsProcessor(AviationPrompt, llm)
results = llm.generate(user_prompts, sampling_params=SamplingParams(max_tokens=100, logits_processors=[logits_processor]))
```

### Expected result:

```shell
No errors
```

### Error message:

```shell
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 372, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 530, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/api.py", line 169, in generate
    logits_processor = JSONLogitsProcessor(AviationPrompt, self.llm)
  File "/usr/local/lib/python3.10/site-packages/outlines/serve/vllm.py", line 122, in __init__
    super().__init__(regex_string, llm)
  File "/usr/local/lib/python3.10/site-packages/outlines/serve/vllm.py", line 54, in __init__
    tokenizer = self.adapt_tokenizer(llm.tokenizer.tokenizer)
AttributeError: 'LLM' object has no attribute 'tokenizer'
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 372, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 530, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/api.py", line 487, in run_batch_inference
    results = list(model.generate.map(question_batches))
  File "/pkg/synchronicity/synchronizer.py", line 335, in _run_generator_sync
    raise uc_exc.exc from None
  File "<ta-Xp14glur4pj88roeBtv1We>:/root/api.py", line 169, in generate
  File "<ta-Xp14glur4pj88roeBtv1We>:/usr/local/lib/python3.10/site-packages/outlines/serve/vllm.py", line 122, in __init__
  File "<ta-Xp14glur4pj88roeBtv1We>:/usr/local/lib/python3.10/site-packages/outlines/serve/vllm.py", line 54, in __init__
AttributeError: 'LLM' object has no attribute 'tokenizer'
```

### Outlines/Python version information:

Using `outlines==0.0.27` and `vllm==0.3.0`.

### Context for the issue:

I can't get it to run without explicitly adding the `adapt_tokenizer` code.

**Comment by lapp0** [comment] 2024-02-08 06:20
Thanks for the issue!

It looks like the code referenced below has an incorrect doc-string, it claims to take an `LLM` but really takes an `LLMEngine`. 

Could you please try

```
logits_processor = JSONLogitsProcessor(AviationPrompt, self.llm.llm_engine)
```

Could you report back whether you still need to re-apply `adapt_tokenizer` in `JSONLogitsProcessor` after making this change?

**Comment by sethkimmel3** [comment] 2024-02-08 06:32
That seemed to do the trick. No longer need to call the `adapt_tokenizer` code.

**Comment by lapp0** [comment] 2024-02-08 06:37
Thanks for testing!

Closing this issue requires
- updating the doc-string
- eliminating the need for an unnecessary `sampler._apply_logits_processors` patch

**Comment by rlouf** [comment] 2024-02-08 15:36
I will modify the code so `RegexLogitsProcessor` accepts a `vllm.LLM` instance instance, it is less cumbersome for users who want to use the logits processor this way.

**Comment by rlouf** [comment] 2024-02-08 16:25
> * eliminating the need for an unnecessary `sampler._apply_logits_processors` patch

What's the status on using `token_ids`? I lost track of the discussions.

**Comment by sethkimmel3** [comment] 2024-02-08 18:41
Not sure if you want me to move this to a separate issue, but this doesn't seem to be fully working. While it does complete, I get results like the following (after removing newlines and extraneous leading/trailing whitespace): 

```
{
{
{
{"is_aviation_related" : false}
{
{"is_aviation_related" : false}
{"is_aviation_related":false}
{
{  "is_aviation_related": false }
{
{"is_aviation_related":false}
{"is_aviation_related": false}
```

It seems like it's enforcing the correct grammar, but may be introducing too much noise (notably newlines) into the response. I tried increasing `max_tokens` to 800, but that didn't seem to improve much.

**Comment by lapp0** [comment] 2024-02-08 18:49
@sethkimmel3 I've observed your issue myself. We need to apply a repetition penalty to prevent the behavior you're observing repeated `\n`. You also may get results by explicitly stating that you're generating json in your prompt.

**Comment by sethkimmel3** [comment] 2024-02-08 19:03
@lapp0 that seems to help! I upped the `repetition_penalty` in the vllm `SamplingParams` to 1.5 and got results like this:

```
{"is_aviation_related": false}
{"is_aviation_related": true}
{ "is_aviation_related" : false }
{"is_aviation_related": false}
{    "is_aviation_related" : false}
{  "is_aviation_related" : false    }
{"is_aviation_related": true}
{  "is_aviation_related" : false }
{"is_aviation_related": true }
{         "is_aviation_related": false}
{"is_aviation_related": true}
{     "is_aviation_related": false}
{"is_aviation_related": false}
{"is_aviation_related":false}
{"is_aviation_related":true}
{"is_aviation_related": false}
{"is_aviation_related":false}
{"is_aviation_related": false}
{  "is_aviation_related": false}
{"is_aviation_related": false}
{ "is_aviation_related":  true }
{"is_aviation_related": false}
{"is_aviation_related": false}
{ "is_aviation_related": false }
```

That being said, it concerns me that there is some amount of non-determinism in whether outlines will return a JSON-formatted response. For what it's worth, I found this project from [this HN post](https://news.ycombinator.com/item?id=37125118). 

Is the implementation for vllm significantly different at a fundamental level that would alter the behavior?

**Comment by rlouf** [comment] 2024-02-08 21:36
These are all valid JSON, as far as I can tell?

**Comment by sethkimmel3** [comment] 2024-02-08 21:58
@rlouf - yes, these are. But I only ran 100 samples through. Before the `repetition_penalty` change, it looked like I got about ~70% JSON output. My concern is that with thousands or millions of samples, there will be a non-zero rate of failure. I want to be able to produce an SQL-like experience, where there at least in structure the output is deterministic

**Comment by lapp0** [comment] 2024-02-08 22:29
@sethkimmel3 outlines guarantees that you will generate valid JSON per your schema. The problem is 
- 1) Transformer-based language models suffer from the "Repetition Problem", previously seen tokens are more likely to be repeated, and as it's repeated more, the probability of it being repeated approaches 1.
- 2) JSON allows for infinite whitespace

These problems combined result in the issue you're describing.

There are a few mitigation strategies, that should be employed to close this issue:
- 1) Allow `no_whitespace` mode in json schema generation
- 2) Document best practices for improving generation quality

**Comment by sethkimmel3** [comment] 2024-02-08 22:47
> outlines guarantees that you will generate valid JSON per your schema

> JSON allows for infinite whitespace

Ha! This seems like a hilarious catch-22. But an important one to solve!

Are these mitigation strategies something you'd like me to try to add? Also @rlouf, you mentioned I should set the value of `outlines.fsm.json_schema.WHITESPACE`. Can you be more specific about how I would do that in my case?

**Comment by lapp0** [comment] 2024-02-08 23:15
@sethkimmel3 could you please try https://github.com/outlines-dev/outlines/pull/625?

`pip install git+https://github.com/lapp0/outlines@allow-single-whitespace-json` then pass `multiple_ws=False` to `JSONLogitsProcessor`. Let me know if the results are better.

**Comment by sethkimmel3** [comment] 2024-02-08 23:41
@lapp0 working on this now - will report shortly.

**Comment by sethkimmel3** [comment] 2024-02-09 00:55
Your branch seems to work without the need for the `repetition_penalty` addition - neat! Thanks for putting this together so quickly.

**Comment by sethkimmel3** [comment] 2024-02-09 01:09
Also worth noting that your solution seems to be much faster. I'm seeing something like ~97 tokens/s, which is significantly faster than what I was seeing with the `repetition_penalty` solution.

**Comment by lapp0** [comment] 2024-02-09 02:07
Glad to hear! 

If there's any speed increase, it's probably because the generation is shorter. A transformers language models generation time complexity is quadratic with the sequence length. Outlines JSON / Regex should already outpace any model on any GPU :)

Please continue contributing issues if you run into any problems as you experiment with outlines!

**Comment by rlouf** [comment] 2024-02-10 12:13
At the end of the day we cannot correct for some of the models' quirks like tendency to repeat themselves, unless we strictly forbid it like @lapp0's PR allows to do. We originally decided to let models choose the number of line breaks and white spaces themselves, because who knows what they've seen during training? While this is OK for larger models, smaller models struggle with this so we will add a section in the documentation to warn users and recommend setting `whitespace_pattern` to the empty string.

Thank you for taking the time to open an issue and following up!

**Closed** 2024-02-10 12:40 UTC
Labels: documentation
