### ISSUE TITLE
Yaml Grammar

### ISSUE THREAD

**Issue by eitanturok** [outlines-dev/outlines#871] opened 2024-05-06 21:18 UTC
The LinkedIn Engineering Team recently [wrote](https://www.linkedin.com/blog/engineering/generative-ai/musings-on-building-a-generative-ai-product) about their experience implementing tool use with LLMs. They explain that they structure every tool call in YAML, not JSON because YAML requires fewer tokens:

> Since the parameters to the call have to match the input schema, we ask the LLM to output them in a structured manner. Most LLMs are trained on YAML and JSON for structured output. We picked YAML because it is less verbose, and hence consumes fewer tokens than JSON.

This seems to be a very important reason to support structured YAML generation.

I found the grammar for YAML [here](https://github.com/yaml/yaml-grammar) and would love for `Outlines` to implement this.

Thoughts?

**Comment by brandonwillard** [comment] 2024-05-09 22:42
This should be possible with [CFG-structured generation](https://outlines-dev.github.io/outlines/reference/cfg/).  There's a `lark` grammar for YAML [here](https://github.com/ligurio/lark-grammars/blob/master/lark_grammars/grammars/yaml.lark), but it might need to be changed in order to properly support any parser restrictions the current CFG-structured generation may have (e.g. LALR(1) only).

In the meantime, we can leave this open for people to try and report any issues or necessary changes.

**Comment by rlouf** [comment] 2024-06-13 07:14
Duplicate of #923

**Closed by rlouf** 2024-06-13 07:14 UTC
Labels: examples, structured generation, grammar
