### ISSUE TITLE
llama.cpp or llama-cpp-python support?

### ISSUE THREAD

**Issue by turian** [outlines-dev/outlines#487] opened 2023-12-28 03:12 UTC
### Presentation of the new feature

[llama.cpp](https://github.com/ggerganov/llama.cpp) is a fast C++ implementation, with support for MANY LLMs, and good MPS support. I believe it is faster than transformers and can support more quantized formats, but this is constantly changing.

[llama-cpp-python](https://github.com/abetlen/llama-cpp-python) is a simple Python binding for it.

Both are *extremely* popular.

### Where does it fit in Outlines?

The GCNF grammar is difficult to specificy and error-prone even when it works.
Outlines would be much more useful.

Outlines only seems to support Transformers, but llama is a very popular alternative engine.

### Are you willing to open a PR?

Not sure, just learning Outlines at this moment.

**Comment by brandonwillard** [comment] 2023-12-28 04:40
This looks like a duplicate of #422.

**Closed by brandonwillard** 2023-12-28 04:40 UTC
